
project_id = "iusvkuescntbclqbtxmn"

[functions.get-users-by-role]
verify_jwt = true

[functions.get-appointment-status-counts]
verify_jwt = true

[functions.get-test-category-counts]
verify_jwt = true

[functions.get-activity-logs]
verify_jwt = true

[functions.get-site-settings]
verify_jwt = false

[functions.update-site-setting]
verify_jwt = true

[functions.log-activity]
verify_jwt = true
