// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iusvkuescntbclqbtxmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1c3ZrdWVzY250YmNscWJ0eG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTMwMTQsImV4cCI6MjA1OTg2OTAxNH0.iE9xxw-tMY_MafU5BrHqKVYfol0nRl-ojQeWo74eR6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);